### ISSUE TITLE
Diagrama de classes com a cardinalidade das entidades.

### ISSUE THREAD

**Issue by ToniMaunde** [Fakul/fakul-laravel#1]
Diagrama de classes com a cardinalidade das entidades, para concluir as MIGRATIONS estabelecendo as RELATIONSHIPS nos MODELS ( hasMany() e belongsTo() ).

**Comment by osvaldoM** [comment]
Vou enviar um  __draft__ de algo que já havia começado a preparar  hoje mais logo @ToniMaunde
